### ISSUE TITLE
Advice for system-wide install?

### ISSUE THREAD

**Issue by cboettig** [yihui/tinytex#1]
Hey @yihui ,

Thanks for the ping, this looks super awesome.  Would definitely like to include this in our `rocker/verse` image (or maybe even the upstream `tidyverse` image since it's fairly small...).  

Your documentation covers a user-level install. While I think most of our rocker users work in single-user containers, it still seems we ought to install it at the system level (as we currently also do for R packages), but it would be nice to make sure the R wrappers around `tlmgr` still work, so I'm curious if you have any advice on that.  I'm thinking I would want to just set the install to maybe `/usr/local/lib/TinyTex` or something, and make that directory owned by the `staff` group (as we do for system R packages) so that any user can install the additional tex files as need.  So, is the `$HOME/.TinyTex` path hard-wired at the moment?

**Comment by yihui** [comment]
I think FAQ 6 and 8 have almost answered your questions. What they didn't answer is how users can install additional packages without the admin privilege, when TeX Live is installed by an admin. I believe there is something equivalent to R's `R_LIBS_USER` variable, but I don't remember how to do it now (should be through`tlmgr conf`). I'll take a look tomorrow.

**Comment by cboettig** [comment]
Thanks, sorry I missed that!  Though I think @hrbrmstr would cringe at the piping random shell script from wget with root privileges, even only in a container script...   (hmm, but I'm probably too lazy to make a separate signed .deb first and not obvious that would be better)

**Comment by yihui** [comment]
I understand that. You don't have to run `sudo` on the whole script. What I recommend you to do is install without `sudo`, and then only use `sudo` to create symlinks to a PATH that is available to all users, e.g., `sudo ln -s ~/.TinyTeX/bin/*/* /usr/local/bin/`.

**Comment by yihui** [comment]
I guess I didn't make it clear enough in FAQ 6. Installing with the `--admin` option only uses `sudo` on `tlmgr path add`:
https://github.com/yihui/tinytex/blob/cc2bed6dda0901d099067d644785d23e8f2e5eb4/tools/install-unx.sh#L27

The rest of the shell scripts does not require `sudo`. And what `sudo tlmgr path add` does is to create symlinks to `/usr/local/bin/`.

**Comment by yihui** [comment]
I just amended [FAQ 6](https://yihui.name/tinytex/faq/) to make it clear how to install without root privileges but make TeX Live available system-wide (you run `sudo` explicitly later).

**Comment by hrbrmstr** [comment]
@cboettig I think documenting that's what happens and also documenting that there is some diligence performed when selecting the distribution site *and* that the sourcing is done over https with a cert signed by a decen't CA wld be fine. I use `homebrew` and — while it's a great ecosystem — it's relatively easy to sneak bad things past it and it has more than a few curl bash pipes in various packages. I do the verification steps I just mentioned by hand when I see new or updated repos with those practices and I'd feel comfortable on personal systems using this approach here.

**Comment by yihui** [comment]
@cboettig Your questions should be fully answered by FAQ 6 and 7 now. You might be disappointed to learn that it is a little complicated.

**Comment by cboettig** [comment]
@yihui Thanks. In FAQ 7 you say users won't be able to install packages themselves in a root setup without using [user mode](https://www.tug.org/texlive/doc/tlmgr.html#USER-MODE), but I don't think that's technically true since we can give users write permission to the tinytex install location without giving them system-wide root privileges (i.e. by adding them to a group that has write permissions only at that location, as we do with R  packages).  Am I missing something?

It does seem like this would require being able to change the default installation directory though, which FAQ 9 tells me I cannot do.  you document installing it first and moving it later, and it sounds like that should work fine? Or will that create trouble for users installing from the R package commands later, because R package won't have the new path?

Sorry for all questions

**Comment by yihui** [comment]
You are absolutely correct that you can add users to a group that has write permission to the TinyTeX root directory. That surely will work, and is based on the assumption that you, as the system admin, trust these users (e.g. researchers in your lab). I was thinking of a more general scenario in which users are random, and we do not want to give them full freedom of modifying the TeX Live installation system-wide.

Yes, FAQ 9 says that you can install it and move it later. TinyTeX is portable, and you can move it anywhere you like. The only thing you need to remember is to create the symlinks to `/usr/local/bin` again via `sudo new/path/to/tlmgr path add`, otherwise the TeX Live executables won't work. As long as the symlinks are created, all users of this system will have access to `tlmgr`, and R users can use `tlmgr_install()` (with `usermode = TRUE` or `FALSE` depending on whether they have write permission to the system-wide installation of TeX Live).

**Comment by yihui** [comment]
@cboettig I just want to make sure you have seen FAQ 8: https://yihui.name/tinytex/faq/ because I saw in your CircleCI build log that some `texlive-*` packages are still installed, which are not necessary and defeats the purpose of TinyTeX. I recommend you to use `equivs-build` to create the dummy package `texlive-local.deb`, instead of downloading the one I created (I provided a prebuilt package only for those who do not know how to build such package).

**Comment by cboettig** [comment]
Good catch, I did see that but forgot to check if any texlive packages were still getting pulled in from other dependencies.  added to the PR now.
