### ISSUE TITLE
detected an existing LaTeX distribution

### ISSUE THREAD

**Issue by ras44** [yihui/tinytex#102]
In reference to https://github.com/rstudio/rmarkdown/issues/39#issuecomment-469644041

I attempted to run `tinytex::install_tinytex()`, but receive:

```
Error: Detected an existing LaTeX distribution (e.g., pdftex is at /usr/bin/pdftex). You have to uninstall it, or use install_tinytex(force = TRUE) if you are sure TinyTeX can override it (e.g., you are a PATH expert or installed TinyTeX previously).
```

There seems to be a conflict between the LaTeX version that is installed by default (via yum builddep R texlive, recommended by RStudio here: https://support.rstudio.com/hc/en-us/articles/218004217-Building-R-from-source), and what is being recommended in the above-referenced issue.  Unless the official recommendation is to install texlive and then force the tinytex installation.

Please let me know if I have misunderstood something.  Thank you for your help.

**Comment by ras44** [comment]
Here is output from the `sudo yum-builddep R`:

```
...
Getting requirements for R-3.5.2-2.el7.src
...
 --> 2:texlive-collection-latexrecommended-svn25795.0-43.20130427_r30134.el7.noarch
 --> texinfo-tex-5.1-5.el7.x86_64
...
```

I believe another possible solution to https://github.com/rstudio/rmarkdown/issues/39#issuecomment-469644041 would be to update the dependency requirements in R-3.5.2-2.el7.src so that texlive-titling, and/or texlive-latexextra is installed, depending on linux flavor.

**Comment by yihui** [comment]
It is a shame that building R from source requires the `textlive` package on your platform. This requirement can be either a convenience or an annoyance. TinyTeX can work in this case (for building R from source). It is just that your system package manager doesn't recognize it. More on this in FAQ 7: https://yihui.name/tinytex/faq/

Anyway, I don't know why you have to build R from source, but the `texlive` package (from `yum`) is not required for building R Markdown to PDF. In your case, you are good to go with `tinytex::install_tinytex(force = TRUE)`.

**Comment by yihui** [comment]
I have turned this error into a warning, since it is not really harmful to have two LaTeX distributions installed on the same machine. The only caveat is when you call LaTeX directly, you may need to know which distribution you are using. For R and **tinytex** package users, there is nothing to worry about since I have taken care of everything behind the scenes (TinyTeX will always be used if installed).

**Comment by ras44** [comment]
One additional thought: if tinytex is required for RStudio's knit-to-pdf functionality, maybe it should be installed on the system when installing RStudio.  Or when running knit-to-pdf and tinytex is not detected, RStudio should test and recommend the installation.

**Comment by yihui** [comment]
It is technically easy to bundle TinyTeX with RStudio. The only problem is that the licenses of LaTeX and its packages are complicated (FAQ 2: https://yihui.name/tinytex/faq/).

TinyTeX is not _required_ but _recommended_ for knitting R Markdown to PDF.

**Comment by JCUSMC** [comment]
I have an existing latex engine that I installed to use Lyx. I've installed tinytex and when I attempt to knit to pdf I get this 


**! Package inputenc Error: Unicode character Â€ (U+0080)
(inputenc)                not set up for use with LaTeX.

Try other LaTeX engines instead (e.g., xelatex) if you are using pdflatex. For R Markdown users, see https://bookdown.org/yihui/rmarkdown/pdf-document.html
Error: Failed to compile StatLearning.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See StatLearning.log for more info.
Execution halted**

I've tried xelatex and that is not the solution. When I use Sys.which('xelatex') and Sys.which('pdflatex') they point to the folder that houses the originally latex engine that I've installed. I don't know if this is all related, has anyone had this issue before? I don't want to uninstall my old latex engine because I still use it for lyx.

**Comment by fkohrt** [comment]
> TinyTeX will always be used if installed

For others who stumble upon this like me: This is due to [`tinytex:::tweak_path`](https://github.com/yihui/tinytex/blob/e9754aa/R/tlmgr.R#L48-L73), which is called [within `tinytex::latexmk`](https://github.com/yihui/tinytex/blob/5b2c192/R/latex.R#L81), which in turn is indirectly called by `rmarkdown::render`. So to really evaluate your *TeX binaries, do something [this](https://github.com/yihui/tinytex/issues/103#issuecomment-470168775).
