### ISSUE TITLE
failed to install on CI

### ISSUE THREAD

**Issue by mickael-kerjean** [yihui/tinytex#114]
Hello, first of thank you for building tinytex, it will be very handy for [my project](https://github.com/mickael-kerjean/filestash) if I manage to get it to work. The installation works fine when performed on my machine but for some reason failed on my CI server with an error message I have no clue how to debug:

```
Automated TeX Live installation using profile: ../tinytex.profile
Loading http://distrib-coffee.ipsl.jussieu.fr/pub/mirrors/ctan/systems/texlive/tlnet/tlpkg/texlive.tlpdb

=============================================================================
../install-tl-20190501/install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2019
 repository: 2018
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via https://tug.org/texlive/doc.)
=============================================================================
rm: cannot remove 'install-tl.log': No such file or directory
sh: 36: cd: can't cd to bin/*
sh: 45: ./tlmgr: not found
mv: cannot stat 'texlive/*': No such file or directory
sh: 20: /root/.TinyTeX/bin/*/tlmgr: not found
sh: 27: /root/.TinyTeX/bin/*/tlmgr: not found
```

Plus for some reason, it seems the profile URL (have no clue what than even is as I just want a workable latex distribution) changes depending on where the install is being perform (I get "http://mirrors.rit.edu/CTAN/systems/texlive/tlnet/tlpkg/texlive.tlpdb" from my laptop), and I have no idea how to troubleshoot this at this stage.

Can you help troubleshoot this? I couldn't find any information anywhere and I already spent many hours without any results

**Comment by yihui** [comment]
This is a tricky time to install TinyTeX (or TeX Live) because a new version of TeX Live was just released two days ago, and it is still being synced to all CTAN mirrors. I'm also having the same problem for my CI, e.g. https://ci.appveyor.com/project/yihui/tinytex/builds/24269356

The problem is that the Net installer was downloaded from one CTAN mirror, but packages could be installed from another mirror. The mirrors are automatically chosen by default, so you could end up with an installer for TeX Live 2019, but then the packages are install from an older mirror that still has TeX Live 2018 packages.

To fix this issue, you need to specify a CTAN mirror. Take a look at https://www.ctan.org/mirrors/mirmon, find one that was last updated a couple of hours ago, and set it via the environment variable `CTAN_REPO`, e.g.

```sh
export CTAN_REPO="http://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet"
curl -sL "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh
```

If you could wait for about three days, I believe most mirrors will be up-to-date, and this issue should be gone automatically.

**Comment by mickael-kerjean** [comment]
It now works + the build is repeatable with the CTAN_REPO env variable! Thank you! 

![screenshot_20190503_105918](https://user-images.githubusercontent.com/13233076/57115489-91c88080-6d92-11e9-96ce-60cab8fadde4.png)

**Comment by yihui** [comment]
From https://www.ctan.org/mirrors/mirmon, most CTAN mirrors should have TeX Live 2019 now, so the `CTAN_REPO` variable should no longer be necessary.

**Comment by mickael-kerjean** [comment]
If possible, I'd rather keep the trick as making the build reproducible is a good feature to have without having to rely on some magic to automatically pick a mirror
