### ISSUE TITLE
tinytex should not assume in can write to /usr/local/bin on Linux

### ISSUE THREAD

**Issue by cboettig** [yihui/tinytex#181]
tinytex assumes it can write symlinks to `/usr/local/bin`. Issue #38 suggests that on MacOS, users typically have permissions to do so, and so perhaps this makes sense as the MacOS behavior.  On Linux platforms, users don't typically have write permission to `/usr/local/bin` and it is often not desirable for regular users to modify `/usr/local/bin`.  

For a bit of context: on Ubuntu, I cannot get `tinytex` installation to work following the root/multi-user recipe we'd worked out on the debian rocker stack (and is documented in the tinytex faq).  I did a clean minimal texlive with a custom texlive profile, https://github.com/noamross/rocker-versioned2/pull/10, that also puts `texlive` under `/opt` and grants users permissions there.  In this setup, `tinytex` can still do it's magic of automatically installing necessary style files with `tlmgr` on `rmarkdown::render`, the only downside is we get a lot of 'false-alarm' error messages about not being able to write to `/usr/local/bin.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
First, [FAQ 5](https://yihui.org/tinytex/faq/) says if the argument `--no-path` is passed to the installation script `install-unx.sh`, it won't generate symlinks to `/usr/local/bin` during installation. I guess you already did this.

Second, when **tinytex** tries to automatically install missing packages, it will also try to run `tlmgr path add`. This is because some LaTeX packages contain executables, and _might_ need to be symlinked. I guess that is why you saw the false-alarm messages. However, I have already suppressed these messages in 8cdaffdcf274fd9a3ac27746f56fa966ad447525, which means you if you are using the latest version of **tinytex** (as requested by the issue guide), you shouldn't see them any more. If you still see them, that's probably a bug of **tinytex**, and I'll need a reproducible example.

Thanks!

**Comment by yihui** [comment]
Oh wait a second; 8cdaffdcf274fd9a3ac27746f56fa966ad447525 doesn't seem to be enough to suppress the messages. Hold on. I'll look further into it.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by kaigu1990** [comment]
Hi, I have a same question.

I used this way `wget -qO- "https://yihui.org/gh/tinytex/tools/install-unx.sh"  | sh -s - --admin --no-path` to install tinytex, and then added symlinks to `/usr/local/bin`. Then I found the lack of 'xcolor.sty', so `tlmgr_search('xcolor.sty')`, and `tlmgr_install('xcolor')`.

But errors happened, `add_link_dir_dir: destination /usr/local/bin not writable, no links from /home/rocheuser/.TinyTeX/bin/x86_64-linux.
tlmgr: An error has occurred. See above messages. Exiting.
add of symlinks had 1 error(s), see messages above.`

Thanks!
