### ISSUE TITLE
What is the best way to remove any dependency on tinytex and install mactex? 

### ISSUE THREAD

**Issue by kundeng** [yihui/tinytex#215]
Hi, this is not a bug but rather a question. 

I had forgotten to install mactex before I tried to install rmarkdown, so now I ended up with tinytex on my system.  I love the idea of a small footprint but tinytex is driving me a bit crazy.  I can't deal with spending hours trying to figure out what packages are missing. 

Can you please provide a concise but accurate guide on 2 things:
1. If I uninstall tinytex and install mactex instead, what should I watch out for?  Will things break?  I saw a few issues that mentioned it will break rmarkdown without some changes. 

2. Is there a way to tell tinytex to auto install missing packages? 
---

By filing an issue to this repo, I promise that

- [X] I have fully read the issue guide at https://yihui.org/issue/.
- [ X] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [X] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by kundeng** [comment]
I started reading the documentation of tinytex.  It seems that it should auto install missing packages for R or Rstudio.  Unfortunately it doesn't do that for me when I use jupyter to generate pdfs. 

Thanks for the great effort, but most modern laptops have enough disk space and I have no patience any more trying to track down missing packages (on windows).  I did that 10 years ago when I just started using latex and it was not fun.

**Comment by yihui** [comment]
> 1. If I uninstall tinytex and install mactex instead, what should I watch out for?  Will things break?  I saw a few issues that mentioned it will break rmarkdown without some changes.

The documentation is here: https://yihui.org/tinytex/ TinyTeX is a (pretty much) self-contained folder. Simply delete it, and you are done.

> 2\. Is there a way to tell tinytex to auto install missing packages?

The documentation is here: https://yihui.org/tinytex/

> I started reading the documentation of tinytex.

If you are new to a tool, it is probably wise to read its manual before spending _hours_ on guessing how it actually works, because reading the manual takes you about ten minutes.

> Unfortunately it doesn't do that for me when I use jupyter to generate pdfs.

If you use TinyTeX to generate PDF _not_ through R, you need to read the documentation: https://yihui.org/tinytex/

> most modern laptops have enough disk space and I have no patience anymore trying to track down missing packages (on windows).

That's fine. It's your choice, and a totally legitimate one. If you don't have the patience, you just run

```sh
tlmgr install scheme-full
```

to install all packages. Then you no longer need to figure out the missing packages by yourself. TinyTeX is tiny by default, but it doesn't mean it can't be huge. If you want everything, it only takes one command line. I probably should add this to the FAQ page (https://yihui.org/tinytex/faq/), but if users don't read the documentation, it won't help.
