### ISSUE TITLE
Percentage bar shows greater than 100%

### ISSUE THREAD

**Issue by ManishBhat** [yihui/tinytex#244]
The percentage bar shows greater than 100%.
![tinytex](https://user-images.githubusercontent.com/9575623/94166373-da616c00-fea8-11ea-8b38-122d162e900b.PNG)

**Comment by cderv** [comment]
This is an issue with the download function indeed. This gives me also a percentage greater than 100%
```r
xfun::download_file("https://github.com/yihui/tinytex-releases/releases/download/v2020.09.19/TinyTeX-1-v2020.09.19.zip")
```
and I think this comes from R itself on windows because I can reproduce with 
```r
tmp_zip <- tempfile(fileext = ".zip")
file_url <- "https://github.com/yihui/tinytex-releases/releases/download/v2020.09.19/TinyTeX-1-v2020.09.19.zip"
# wrong percentage
download.file(file_url, tmp_zip, method = 'libcurl')
# correct percentage
download.file(file_url, tmp_zip, method = 'wininet')
```

with libcurl the percentage calculated by `download.file` is not correct on windows
```r
> download.file(file_url, tmp_zip, method = 'libcurl')
essai de l'URL 'https://github.com/yihui/tinytex-releases/releases/download/v2020.09.19/TinyTeX-1-v2020.09.19.zip'
Content length 651 bytes
```

Let's ,note on ubuntu, it is ok
```r
> download.file(file_url, tmp_zip, method = 'libcurl')
trying URL 'https://github.com/yihui/tinytex-releases/releases/download/v2020.09.19/TinyTeX-1-v2020.09.19.zip'
Content type 'application/octet-stream' length 98904845 bytes (94.3 MB)
````

This should be moved into `xfun` package if we want to fix this on windows by not trying libcurl first maybe

**Comment by yihui** [comment]
You can either wait for the next CRAN release of the **xfun** package, or install the development version via

```r
remotes::install_github('yihui/xfun')
```

if you have [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed.

**Comment by ManishBhat** [comment]
Thanks, @yihui @cderv for your prompt and detailed responses!
