### ISSUE TITLE
Is there any way to suppress warning in tinytext?

### ISSUE THREAD

**Issue by fgoerlich** [yihui/tinytex#256]
I get a lot of
```
LaTeX Warning: Label `tab:table' multiply defined.
LaTeX Warning: There were multiply-defined labels. 
```
but I know that the multiply-defined labels are not a cuase of concern.
Is there any way to suppress these warnings.

Thanks,

**Comment by cderv** [comment]
Hi, 

This is a warning by Latex itself when the document is render to PDF, not by **tinytex**. It should be only shown in the console while rendering and not in a document or else. 

I understand `\labels` are meant to provide identifiers, that can be then referred to via commands such as` \ref`, so they are expected to be unique. It is not good practice to have duplicate, and could cause error - that is why Latex is throwing a warning. 

If you want to ignore this warning, you can but it will still be printed unless you solve it I think. That is what warnings are for. You may be able to remove the warnings by changing the way Latex verbose output, but I don't think this could be specific to THIS warning unless you solve it. 

Anyway, this is not a tinytex issue nor a feature request. Per the [issue guide](https://yihui.org/issue/#got-a-question), Stackoverflow, RStudio Community or any QA site will be better place for this, If you search for this warning on Google, you'll found a lot of answer. 

If you think there is an underlying issue. In this case, you can provide a reproducible example so that we investigate.

Thank you.

**Comment by yihui** [comment]
I'm fine with providing a global R option `options(tinytex.latexmk.warning = FALSE)` to suppress the warnings on the R side: https://github.com/yihui/tinytex/blob/e1b43e503642bde86f00ec6428eb7f2e0faca566/R/latex.R#L376

If either of you want to submit a PR, please feel free to (don't' forget to document it in a NEWS item). Thank!

**Comment by yihui** [comment]
With the development version:

```r
remotes::install_github('yihui/tinytex')
```

you can set `options(tinytex.latexmk.warning = FALSE)` in your `.Rprofile` to avoid the warnings.
