### ISSUE TITLE
Error when installing a package 

### ISSUE THREAD

**Issue by stanleesocca** [yihui/tinytex#261]
Hi, 

I run into some error message when Installing most package(s) I will love to use using tinytex. Its been a long drawn issue and I haven't found a way to by pass-by it. 

Can you help me on this. 

Stanley 

```
tlmgr_install("lmodern")
tlmgr install lmodern
tlmgr.pl install: package lmodern not present in repository.
tlmgr.pl: action install returned an error; continuing.
tlmgr.pl: package repository https://distrib-coffee.ipsl.jussieu.fr/pub/mirrors/ctan/systems/texlive/tlnet (verified)
tlmgr.pl: An error has occurred. See above messages. Exiting.
tlmgr update --self
tlmgr install lmodern
tlmgr.pl install: package lmodern not present in repository.
tlmgr.pl: action install returned an error; continuing.
tlmgr.pl: package repository https://distrib-coffee.ipsl.jussieu.fr/pub/mirrors/ctan/systems/texlive/tlnet (verified)
tlmgr.pl: An error has occurred. See above messages. Exiting.
```

**Comment by cderv** [comment]
Hi, 

The issue seems pretty clear to me 

> tlmgr.pl install: package lmodern not present in repository.

`lmodern` does not seem to be a CTAN package. Quick google search: https://www.google.com/search?q=CTAN+lmodern

It shows this is related to the `lm` package.

I believe you tried to installed it because `lmodern.sty` was missing. 

Know that this function can help find the package: 
``` r
tinytex::parse_packages(files = "lmodern.sty")
#> tlmgr search --file --global "/lmodern.sty"
#> [1] "lm"
```

And you have `tinytex::parse_install` as a wrapper that also do the installation

This will look for the CTAN package that contains the sty file and install it if missing
```r
tinytex::parse_install(files = "lmodern.sty")
```

I'll close this, but reopen if I missed something.
