### ISSUE TITLE
GHA issue when installing TinyTeX

### ISSUE THREAD

**Issue by cderv** [yihui/tinytex#270]
And again we got an issue with TinyTeX download on Windows:

```
C:\Users\RUNNER~1\AppData\Local\Temp>powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest $Env:TINYTEX_URL -OutFile install.zip" 
Invoke-WebRequest : Unable to read data from the transport connection: An existing connection was forcibly closed by 
the remote host.
```

here:  https://github.com/yihui/tinytex/runs/1742477061#step:5:34

Reported here: https://github.com/r-lib/actions/issues/213

We could try the new action I made: https://github.com/cderv/actions/tree/tinytex-bin/setup-tinytex-bin

It downloads the last binary from Github release page.

**Comment by yihui** [comment]
Please feel free to switch to the new action.

**Comment by cderv** [comment]
Yep, it is a little bit experimental but maybe it will help to download directly from the github release. I'll do it soon;

**Comment by yihui** [comment]
Since this problem has occurred many times, I'm all for switching to TinyTeX in its Github releases instead of downloading from AppVeyor, if the former can be downloaded more reliably.

Another possible solution is to retry the download a few more times if it fails: https://github.com/yihui/tinytex/blob/149f7e7084734af5323fb1629d9e1ec1fbde8b36/tools/install-bin-windows.bat#L19 which is probably what we should do anyway because this problem may not be unique to Github Actions. This only involves a `for` loop, so you want to try this solution first.

**Comment by cderv** [comment]
Oh yeah that could be interesting to have a retry. I'll try this first in bat file.

**Comment by cderv** [comment]
This should have been fixed in #276 (we hope 🤞 )

**Comment by cderv** [comment]
Still an issue it seems: https://github.com/yihui/knitr/pull/1960

**Comment by cderv** [comment]
Happens also in other repo 😞 like https://github.com/rstudio/rmarkdown/runs/1920401189

**Comment by yihui** [comment]
I guess 72128f301a51a993008bb54475d6d5d021e6301e should fix it. GHA should be able to download assets from Github releases. I'm closing this issue for now.
