### ISSUE TITLE
Feature request: expanded error message about uninstalling other distributions

### ISSUE THREAD

**Issue by AmeliaMN** [yihui/tinytex#275]
I am having trouble debugging tinytex, and the part I am getting stuck on is this error message, which I get when I run `tinytex::reinstall_tinytex()`. 

> Warning message:
Detected an existing tlmgr at /Library/TeX/texbin/tlmgr. It seems TeX Live has been installed (check tinytex::tinytex_root()). You are recommended to uninstall it, although TinyTeX should work well alongside another LaTeX distribution if a LaTeX document is compiled through tinytex::latexmk().

I honestly don't know what it means to "uninstall it." I can see files in the folder /Library/TeX/texbin/tlmgr. Do I just delete those? I would guess they came from my other LaTeX installation, which came with TeXShop. Maybe I need to uninstall TeXShop? I am nervous about uninstalling TeXShop, because I do use it for straight .tex files, although I guess I could just make .Rnw files with no R code and compile them in RStudio. 

My ideal world would be one in which I could compile .tex files in TeXShop, and .Rmd and .Rnw files in RStudio. Probably I only need one LaTeX installation to accomplish this, but I think I've had two. (I've successfully done this for a period of time in the past, so something changed in my setup since the last time I compiled a PDF in RStudio...) I'd guess I'm not the only person who would get stressed by this error message, so I'm submitting this as a feature request for more clarity in the message and/or a bit in the FAQ about it.

In case it's useful,

```
> xfun::session_info('tinytex')
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 1.3.1073

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  graphics_4.0.2  grDevices_4.0.2 stats_4.0.2     tinytex_0.29    tools_4.0.2     utils_4.0.2    
  xfun_0.20    
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by AmeliaMN** [comment]
(Thrilling update-- my problem turned out to be from the preamble I was using through `includes:` Haven't tracked down the actual issue, but it compiles fine without it. But, this feature request still stands! I think "uninstall" is ambiguous, especially with something like LaTeX that has its hooks in everywhere.)

**Comment by cderv** [comment]
Thanks for the feature request. The hard part is to give better uninstalling instruction because we don't really know which other distribution a user would have. But for sure we can make this error message and its context clearer. 

FWIW, you can also compile `.tex` file in RStudio IDE. If you open one, you'll have a Compile to PDF button. 
This will compile to PDF using the TeX distribution of your system (on your PATH I believe)
In the option, you can now (since 1.4) also choose to compile using **tinytex** with `tinytex::latexmk()`. This will make use of the TinyTeX distribution installed in this case.

**Comment by yihui** [comment]
> I honestly don't know what it means to "uninstall it."

You seem to be using MacTeX, so http://www.tug.org/mactex/uninstalling.html This also shows one advantage of TinyTeX---if you were to uninstall TinyTeX, you don't need to read so many instructions but simply run `tinytex::uninstall_tinytex()` :)

Anyway, this warning is pretty much legacy now. It was added in an old version of **tinytex** to make users aware of existing LaTeX distributions, because when more than one LaTeX distribution exists in the same system, you may not really know which one you are using, unless you carefully check the `PATH` variable. In the case of macOS, TinyTeX's binaries are symlinked to `/usr/local/bin`, which I believe has higher precedence than `/Library/TeX/texbin` in `PATH`. You may run `echo $PATH` in the terminal to verify it (`/usr/local/bin` should appear before `/Library/TeX/texbin`).

So it's probably time to retire this warning message now. The downside is that you may never know that you still have N times 5Gb of MacTeX left over on your computer that you no longer use (N = #years of installation). That is probably better than scaring or confusing users with this message.
