### ISSUE TITLE
bug in cleaning auxiliary files when emulation=TRUE

### ISSUE THREAD

**Issue by guang-yu-zhu** [yihui/tinytex#281]
Hi,

I noticed that if I run
latexmk(file,emulation =TRUE)
It will clean all other auxiliary files but not the one with extension as log.
And if I run
latexmk(file,emulation =FALSE)
Then this problem is solved.

I guess there is something wrong with the emulation step. Could you fix this bug?

**Comment by yihui** [comment]
The log file is kept when LaTeX runs into either errors or warnings. I just made a change so that if you set `options(tinytex.latexmk.warning = FALSE)` in your `~/.Rprofile`, the log file will be cleaned up even if contains warnings.

That said, warnings might actually need your attention, and I recommend that you take a look at the log file to make sure the warnings can be safely ignored before deciding to delete the file.
