### ISSUE TITLE
offline installation

### ISSUE THREAD

**Issue by Matth92ias** [yihui/tinytex#312]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

I am running into the same problem as mentioned in the issue 121 (https://github.com/yihui/tinytex/issues/121). When executing the function tinytex::install_tinytex() my Proxy does not allow me to download the .tar.gz file. 
Unfortunately the function tinytex:::install_windows_zip does not seem to exist anmyore. I found the following post on stackoverflow https://stackoverflow.com/questions/66494997/how-to-install-tinytex-from-zip-file-install-windows-zip-not-working where a user commented that the function is probably removed from the package.
Is there another option for an offline installation or could you add the function to the package?

**Comment by cderv** [comment]
Thanks for opening this in a new issue. 

You can use `tinytex:::install_prebuilt()` on the file you downloaded from https://github.com/yihui/tinytex-releases/releases. Would that work for you ? 

About proxy, you may just need to configured it in R so that file can be downloaded from R behing a proxy. See **Setting Proxies** in `?download.file`. If this is possible for you, you would not have anymore error about proxy from R.

**Comment by Matth92ias** [comment]
Thanks for the quicke reply! that works perfectly.

**Comment by linlennypinawa** [comment]
Would either @cderv or @Matth92ias share r code chunks for me to get started with?  I am figuring out the arguements in tinytex:::install_prebuilt().

**Comment by cderv** [comment]
@linlennypinawa see my answer 
> You can use `tinytex:::install_prebuilt()` on the file you downloaded from [yihui/tinytex-releases/releases](https://github.com/yihui/tinytex-releases/releases). Would that work for you ?

This means you need to download a bundle and use the function to install it. 

Source code is here otherwise: https://github.com/rstudio/tinytex/blob/3495cb88d8e059afbe443f09370f0dcbfb9e44d0/R/install.R#L411-L415

That is the beauty of Open Source project, you can see the code source to understand how this work. 


Though, this is advanced usage. `install_prebuilt()` is an unexported function (hence the `:::` in `tinytex:::install_prebuilt()` and why undocumented). It shouldn't be used except on very specific situation like offline server for example. 

Hope it helps
