### ISSUE TITLE
Error when compile RMarkdown pdf file with package `vtable`

### ISSUE THREAD

**Issue by tacitli** [yihui/tinytex#339]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by tacitli** [comment]
I encounter errors when running the following simple code in RMarkdown. 

    ---
    title: "debugging"
    author: ""
    date: "11/12/2021"
    output: pdf_document
    ---
    
    ```{r}
    library(vtable)
    st(iris,out="kable")
    ```


I am using the latest version of `tinytex` and all R packages. 

The error message looks like:

> ! Misplaced \noalign. \bottomrule ->\noalign 
>                        {\ifnum 0=`}\fi \@aboverulesep =\aboverulesep \global... l.168 \bottomrule
> 
> Error: LaTeX failed to compile debug.tex. See
> https://yihui.org/tinytex/r/#debugging for debugging tips. See
> debug.log for more info. Execution halted

or

> I was unable to find any missing LaTeX packages from the error log
> manual.log. ! Misplaced \noalign. \addlinespace ->\noalign 
>                          {\ifnum 0=`}\fi \@ifnextchar [{\@addspace }{\@addsp... l.190 \addlinespace
> 
> Error: LaTeX failed to compile manual.tex. See
> https://yihui.org/tinytex/r/#debugging for debugging tips. See
> manual.log for more info. In addition: 
> Warning messages: 
> 1: package'vtable' was built under R version 3.6.2  
> 2: package 'kableExtra' was built under R version 3.6.2  Execution halted

in my origin rmd file with similar code (different data frame).

**Comment by tacitli** [comment]
original post on stack overflow: https://stackoverflow.com/questions/69951578/error-when-compile-rmarkdown-pdf-file-with-package-vtable

**Comment by cderv** [comment]
I believe this is an issue in the **vtable** package. Did you ask there first ? 
Usually, you need to dig into the function that will create an error. Here you are asking **vtable** to write the table in your LaTeX output for you using `vtable::st()`. It is probably that something is wrong in the way the table is created as you have an issue in the LaTeX syntax produced. 

**tinytex** is only here to run the conversion from tex to PDF using LaTeX - if the code produced in the `tex` file by the function used, then **tinytex** will report back the error from LaTeX conversion. 

Here, **vtable** will write for you the LaTeX code using some logic in the code. Repo is here https://github.com/NickCH-K/vtable

I looked into this a bit and this is the LaTeX code produced: 
````latex
\begin{table}

\caption{\label{tab:unnamed-chunk-1}Summary Statistics}
\centering
\begin{tabular}[t]{llllllll}
\toprule
Variable & N & Mean & Std. Dev. & Min & Pctl. 25 & Pctl. 75 & Max\\
\midrule
Sepal.Length & 150 & 5.843 & 0.828 & 4.3 & 5.1 & 6.4 & 7.9\\
Sepal.Width & 150 & 3.057 & 0.436 & 2 & 2.8 & 3.3 & 4.4\\
Petal.Length & 150 & 3.758 & 1.765 & 1 & 1.6 & 5.1 & 6.9\\
Petal.Width & 150 & 1.199 & 0.762 & 0.1 & 0.3 & 1.8 & 2.5\\
Species & 150 &  &  &  &  &  & \\
\addlinespace
... setosa & 50 & 33.3% &  &  &  &  & \\
... versicolor & 50 & 33.3% &  &  &  &  & \\
... virginica & 50 & 33.3% &  &  &  &  & \\
\bottomrule
\end{tabular}
\end{table}
````

As you see, some cell value will be `33.3%` and here `%` is not escaped. I believe it should be `33.3\%` because `%` is a special character in LaTeX. 

From my debugging phase, I think the code goes through here 
https://github.com/NickCH-K/vtable/blob/e3bfe9bff370b164007289c892682aefd72e958e/R/helpers.R#L370
where `knitr::kable()` is used but `escape = FALSE` is set. 

What is happening internally ? 

````markdown
---
title: "debugging"
author: ""
date: "11/12/2021"
output: 
  pdf_document:
    keep_tex: true
    extra_dependencies: booktabs
---

dataframe produced by  `st()` internally. Found while debugging and formatted as using **datapasta** R package

```{r}
df <- data.frame(
  stringsAsFactors = FALSE,
       check.names = FALSE,
          Variable = c("Sepal.Length","Sepal.Width",
                       "Petal.Length","Petal.Width","Species","... setosa",
                       "... versicolor","... virginica"),
                 N = c("150", "150", "150", "150", "150", "50", "50", "50"),
              Mean = c("5.843","3.057","3.758",
                       "1.199",NA,"33.3%","33.3%","33.3%"),
       `Std. Dev.` = c("0.828", "0.436", "1.765", "0.762", NA, NA, NA, NA),
               Min = c("4.3", "2", "1", "0.1", NA, NA, NA, NA),
        `Pctl. 25` = c("5.1", "2.8", "1.6", "0.3", NA, NA, NA, NA),
        `Pctl. 75` = c("6.4", "3.3", "5.1", "1.8", NA, NA, NA, NA),
               Max = c("7.9", "4.4", "6.9", "2.5", NA, NA, NA, NA)
)

```

Code use to produce LaTeX table 

```{r}
knitr::kable(df, caption = "Title", row.names = FALSE, 
      format = "latex", booktabs = TRUE, escape = FALSE)
```

````

This will error because `%` in column mean are not escaped. 




Changing last chunk to use `escape = TRUE` makes it work
```r
knitr::kable(df, caption = "Title", row.names = FALSE, 
      format = "latex", booktabs = TRUE, escape = TRUE)
```

I would suggest to open an issue in **vtable**. 

There is nothing much we can do here in **tinytex**. Hence, I'll close this issue
