### ISSUE TITLE
Opening Rmd files in R Studio leaves a "nul" File Residue In Directory

### ISSUE THREAD

**Issue by drag05** [yihui/tinytex#371]
Please see Issue #10581 posted on R Studio [here](https://github.com/rstudio/rstudio/issues/10581) and R Studio's response in reference to latex.
Thank you!

**Comment by yihui** [comment]
Probably duplicate of #354 (which has been fixed in **tinytex**). To verify, you may first check `Sys.which('curl')`. If it points to the `curl.exe` from RTools, it might be the same issue.

However, [you said](https://github.com/rstudio/rstudio/issues/10581#issuecomment-1115235179):

> Per my first comment, the nul file appeared just by opening the Rmd file and not running it.

If the file is created every time you simply _open_ an Rmd file, I doubt if this has anything to do with **tinytex**, unless RStudio silently calls `tlmgr` when you open an Rmd file.

You may try to set the environment variable `TEXLIVE_PREFER_OWN` to `1` in your system, quit and open RStudio again, then see if it helps.

**Comment by drag05** [comment]
@yihui Thank you for the prompt reply and advice! `Sys.which()` points to `curl.exe` in `Windows32`.  Entering the new system environment variable seems to be working. No `nul` showed up neither before  nor after rendering. I will link your answer to RStudio/issues. 
The next interesting information would be what 'MS DOS error' was referring to in regard to the `nul` file. 
Thank you!

**Comment by drag05** [comment]
@yihui  I have deleted them using command line

```
C:\>del \\.\C:\path\to\nul
```
Thank you!

**Comment by yihui** [comment]
Great! Then I suppose this issue can be closed now?

**Comment by drag05** [comment]
@yihui  yes!

**Comment by dpc-michaelean-odonnell** [comment]
I have also had this issue and appreciate the dicussion above.
