### ISSUE TITLE
versioning tinytex?

### ISSUE THREAD

**Issue by cboettig** [yihui/tinytex#71]
I noticed that `install_tinytex` functions points always to the latest master branch of GitHub. 

I think it would be preferable if the R function loaded the tools script bundled directly in the package, rather than from the most recent GitHub copy? (e.g. https://github.com/yihui/tinytex/blob/master/R/install.R#L95 why not `system.file()` instead?), and if the tools script itself could do likewise? or at least point tagged releases instead?)  Maybe that doesn't matter much. 

I realizing versioning the tinytex libraries itself is a different issue, might also be something to think about.

**Comment by yihui** [comment]
Given the fact that `install_tinytex()` always installs the latest version of TeX Live, versioning those simple (shell/batch) scripts under `tools/` do not really make much practical sense -- they are very unlikely to change substantially, and what they do is pretty much downloading the TeX Live installer.

I intentionally used the latest master version because that way gives much more freedom to update them anytime I need to. If I use `system.file()`, I'll have to beg CRAN's pardon in case I find serious problems in any of these scripts.

**Comment by cboettig** [comment]
Ah, yeah, that makes sense.
